package com.whb.simplefiledownload.managedownload.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whb.simplefiledownload.managedownload.SimpleDownLoadInfo;

import com.whb.simplefiledownload.managedownload.greendao.SimpleDownLoadInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig simpleDownLoadInfoDaoConfig;

    private final SimpleDownLoadInfoDao simpleDownLoadInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        simpleDownLoadInfoDaoConfig = daoConfigMap.get(SimpleDownLoadInfoDao.class).clone();
        simpleDownLoadInfoDaoConfig.initIdentityScope(type);

        simpleDownLoadInfoDao = new SimpleDownLoadInfoDao(simpleDownLoadInfoDaoConfig, this);

        registerDao(SimpleDownLoadInfo.class, simpleDownLoadInfoDao);
    }
    
    public void clear() {
        simpleDownLoadInfoDaoConfig.clearIdentityScope();
    }

    public SimpleDownLoadInfoDao getSimpleDownLoadInfoDao() {
        return simpleDownLoadInfoDao;
    }

}
